# Generated by Django 4.2.6 on 2023-10-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_user_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='place',
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='pos.employee')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_at', to='pos.place')),
            ],
        ),
    ]
