# Generated by Django 4.2.6 on 2023-10-29 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_manager_alter_employeeprofile_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmanagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submanger', to='pos.place')),
                ('submanager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='s_data', to='pos.submanager')),
            ],
        ),
    ]
