# Generated by Django 4.2.6 on 2023-10-29 21:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_port_store_place_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplyer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pos.place',),
            managers=[
                ('supplyer', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='role',
            field=models.CharField(choices=[('STORE', 'Store'), ('PORT', 'Port'), ('SUPPLYER', 'Supplyer')], max_length=50),
        ),
        migrations.CreateModel(
            name='SupplyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sup_detail', to='pos.supplyer')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='s_detail', to='pos.store')),
            ],
        ),
        migrations.CreateModel(
            name='PortProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p_detail', to='pos.port')),
            ],
        ),
    ]
