# Generated by Django 4.2.6 on 2023-10-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_supplyer_transaction_date_transaction_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='place',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='place',
        ),
        migrations.RemoveField(
            model_name='submanagerprofile',
            name='place',
        ),
        migrations.RemoveField(
            model_name='submanagerprofile',
            name='submanager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='SubManager',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='ManagerProfile',
        ),
        migrations.DeleteModel(
            name='SubmanagerProfile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
