# Generated by Django 4.2.6 on 2023-10-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_supplytrans_delete_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='supplyTrans',
            new_name='Transaction',
        ),
    ]
