# Generated by Django 4.2.6 on 2023-10-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_product_supplyer_alter_transaction_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
