# Generated by Django 4.2.6 on 2023-10-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_alter_productdetail_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
